Repository Quad8/quad8-front, pull requests merged in 2024-05, with the labels that each got.

#2 [Feat] Next.js 설치 & globals 세팅 및 GitHub템플릿 추가
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labeler-config.yml
  .github/labels.json
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-review-assign-pr.yml
  .github/workflows/aws-dev-deploy.yml
  .github/workflows/issue-pr-labeler.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc.js
  .settings.json
  .storybook/main.ts
  .storybook/preview.ts
  .stylelintrc.json
  README.md
  appspec.yml
  deploy.sh
  next.config.mjs
  package-lock.json
  package.json
  public/images/.gitkeep
  public/svgs/.gitkeep
  src/app/bk/page.tsx
  src/app/dw/page.tsx
  src/app/layout.tsx
  src/app/mj/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/ye/page.tsx
  src/app/yj/page.tsx
  src/components/.gitkeep
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/_globals.scss
  src/styles/globals/_colors.scss
  src/styles/globals/_fonts.scss
  src/styles/globals/_mixin.scss
  src/styles/globals/_zindex.scss
  src/styles/reset.css
  svgr.d.ts
  tsconfig.json
Labels: ⚙ Setting

#4 [Fix] husky lint stage 수정 => styleLint 분리
  .github/labeler-config.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-review-assign-pr.yml
  package.json
  src/app/bk/page.module.scss
  src/app/bk/page.tsx
Labels: 🐞 Fix

#10 [Fix] style & es lint 설정 변경
  .eslintrc.json
  .github/workflows/auto-review-assign-pr.yaml
  .stylelintrc.js
  .stylelintrc.json
  package-lock.json
  package.json
  src/styles/reset.css
Labels: 🐞 Fix

#17 [Feat] 게시글 작성/ 리뷰 등록 / 게시글 수정 공통 모달창 디자인 구현
  public/svgs/camera.svg
  public/svgs/deleteImage.svg
  src/app/mj/customData.ts
  src/app/mj/page.module.scss
  src/app/mj/page.tsx
  src/app/types/CustomKeyboardTypes.ts
  src/components/WriteEditModal/ImageInput.module.scss
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.module.scss
  src/components/WriteEditModal/KeyboardInfoBox.tsx
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/buttons/TwoButton/TwoButton.module.scss
  src/components/buttons/TwoButton/TwoButton.tsx
  src/constants/writeEditModalType.ts
Labels: ✨ Component

#16 [Feat] 모달 컴포넌트 구현
  .stylelintrc.js
  src/app/providers.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/hooks/useOutsideClick.ts
Labels: ✨ Component
