Repository Quad8/quad8-front, pull requests merged in 2024-06, with the labels that each got.

#21 [Feat, Chore] Rating 별점 컴포넌트 구현, eslint, prettier 변경
  .eslintrc.json
  .husky/commit-msg
  .prettierrc.js
  public/svgs/star.svg
  src/app/layout.tsx
  src/app/mj/page.tsx
  src/app/providers.tsx
  src/app/yj/page.tsx
  src/components/Header/CartButton.module.scss
  src/components/Header/CartButton.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Header/LoginButton.tsx
  src/components/Header/LogoutButton.tsx
  src/components/Header/SearchBox.module.scss
  src/components/Header/SearchBox.tsx
  src/components/Header/ShopButton.module.scss
  src/components/Header/ShopButton.tsx
  src/components/Modal/Modal.tsx
  src/components/Rating/Rating.module.scss
  src/components/Rating/Rating.tsx
  src/components/WriteEditModal/ImageInput.module.scss
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.module.scss
  src/components/WriteEditModal/KeyboardInfoBox.tsx
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/buttons/TwoButton/TwoButton.module.scss
  src/components/buttons/TwoButton/TwoButton.tsx
  src/styles/globals/_colors.scss
Labels: ⚙ Setting, ✨ Component

#23 [Refactor] 게시글 작성/ 리뷰 등록 / 게시글 수정 공통 모달창 수정
  public/svgs/upArrow.svg
  src/app/mj/page.module.scss
  src/app/mj/page.tsx
  src/components/WriteEditModal/ImageInput.module.scss
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.module.scss
  src/components/WriteEditModal/KeyboardInfoBox.tsx
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/buttons/ScrollUpButton/ScrollUpButton.module.scss
  src/components/buttons/ScrollUpButton/ScrollUpButton.tsx
  src/components/buttons/TwoButton/TwoButton.tsx
  src/constants/writeEditModalType.ts
  src/types/CustomKeyboardTypes.ts
Labels: 🔨 Refactor

#19 [Feat] scroll up button 구현
  src/app/mj/page.module.scss
  src/app/mj/page.tsx
  src/app/providers.tsx
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/buttons/ScrollUpButton/ScrollUpButton.tsx
  src/components/buttons/TwoButton/TwoButton.tsx
Labels: ✨ Component

#32 [Feat] input text dropdown field 제작
  .github/workflows/aws-dev-deploy.yml
  .settings.json
  deploy.sh
  next.config.mjs
  public/index.ts
  public/svgs/.gitkeep
  public/svgs/arrowDown.svg
  public/svgs/eyeOff.svg
  public/svgs/eyeOn.svg
  src/app/bk/page.tsx
  src/components/.gitkeep
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/InputFiled.module.scss
  src/components/RadioField/RadioField.module.scss
  src/components/RadioField/RadioField.tsx
  src/components/TextField/TextField.module.scss
  src/components/TextField/TextField.tsx
  src/components/index.ts
  src/components/parts/ErrorMessage.module.scss
  src/components/parts/ErrorMessage.tsx
  src/components/parts/Input.module.scss
  src/components/parts/Input.tsx
  src/components/parts/Label.module.scss
  src/components/parts/Label.tsx
  src/components/parts/Radio.tsx
  src/components/parts/SuffixIcon.module.scss
  src/components/parts/SuffixIcon.tsx
  src/components/parts/SuffixUnit.module.scss
  src/components/parts/SuffixUnit.tsx
  src/components/parts/Textarea.module.scss
  src/components/parts/Textarea.tsx
  src/components/parts/index.ts
  src/styles/globals/_fonts.scss
Labels: ✨ Component

#39 [Fix] 모달 투명도 문제 수정 헤더 아이콘 변경
  public/svgs/logo.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header/CartButton.module.scss
  src/components/Header/CartButton.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Header/SearchBox.module.scss
  src/components/Header/ShopButton.module.scss
  src/components/Header/ShopButton.tsx
  src/components/Modal/Modal.module.scss
  src/middleware.ts
  src/styles/globals/_fonts.scss
Labels: 🐞 Fix, 🎨 Style

#40 [Feat] 찜, 좋아요 버튼구현
  public/svgs/heart.svg
  public/svgs/thumb.svg
  src/app/yj/page.tsx
  src/components/buttons/LikeButton/LikeButton.module.scss
  src/components/buttons/LikeButton/LikeButton.tsx
Labels: ✨ Component

#34 [Feat] 상품 아이템 컴포넌트 구현
  src/app/ye/page.tsx
  src/components/Products/ProductItem.module.scss
  src/components/Products/ProductItem.tsx
Labels: ✨ Component

#36 [Feat] Pagination 컴포넌트 구현
  public/svgs/caretLeft.svg
  public/svgs/caretRight.svg
  src/app/ye/page.tsx
  src/components/Pagination/Pagination.module.scss
  src/components/Pagination/Pagination.tsx
  src/components/WriteEditModal/ImageInput.module.scss
  src/libs/calculatePage.ts
  src/styles/_globals.scss
  src/styles/globals/_media.scss
  src/styles/globals/_mixin.scss
Labels: ✨ Component

#42 [Feat] 버튼 구현
  src/app/mj/page.module.scss
  src/app/mj/page.tsx
  src/app/providers.tsx
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/ScrollUpButton/ScrollUpButton.module.scss
  src/components/ScrollUpButton/ScrollUpButton.tsx
  src/components/WriteEditModal/ImageInput.module.scss
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.module.scss
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/buttons/TwoButton/TwoButton.module.scss
  src/components/buttons/TwoButton/TwoButton.tsx
  src/components/index.ts
Labels: ✨ Component

#47 [Feat] dropdown xs size 추가 및 일부 수정
  .github/workflows/aws-dev-deploy.yml
  .husky/commit-msg
  .storybook/main.ts
  .storybook/preview.ts
  deploy.sh
  package-lock.json
  package.json
  public/svgs/arrowDown.svg
  src/app/bk/page.module.scss
  src/app/bk/page.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.stories.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/index.stories.tsx
  src/components/ItemOverview/ItemOverview.module.scss
  src/components/ItemOverview/ItemOverview.tsx
  src/components/RadioField/RadioField.tsx
  src/components/RadioField/index.stories.tsx
  src/components/TextField/TextField.module.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/index.stories.tsx
  src/components/index.ts
  src/components/parts/Input.module.scss
  src/components/parts/Input.tsx
  src/components/parts/Label.tsx
  src/components/parts/Radio.tsx
  src/components/parts/SuffixIcon.module.scss
  src/components/parts/SuffixIcon.tsx
  src/components/parts/Textarea.module.scss
  src/components/parts/Textarea.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/globals/_fonts.scss
Labels: ✨ Component

#48 [Feat] main hero 컴포넌트 구현
  .nvmrc
  public/images/heroItem1.png
  public/images/heroItem2.png
  public/images/heroItem3.png
  public/images/heroItem4.png
  public/images/heroItem5.png
  public/images/heroItem6.png
  src/app/_components/Hero.module.scss
  src/app/_components/Hero.tsx
  src/app/_components/heroItem.ts
Labels: 📖 Page, ✨ Component

#61 Fix: Input 관련 컴포넌트 사이즈 재정리
  src/components/InputField/InputField.tsx
  src/components/parts/Input.module.scss
  src/components/parts/Label.tsx
  src/components/parts/Radio.tsx
Labels: 🐞 Fix

#52 [Feat] 커스텀 키보드 페이지 기본 기능 구현
  next.config.mjs
  package-lock.json
  package.json
  public/glbs/keyboard.glb
  public/glbs/tklKeyboard.glb
  public/svgs/crossCircle.svg
  public/svgs/deleteTag.svg
  public/svgs/stepComplete.svg
  src/app/custom-keyboard/_components/BoardOption.module.scss
  src/app/custom-keyboard/_components/BoardOption.tsx
  src/app/custom-keyboard/_components/ColorTag.module.scss
  src/app/custom-keyboard/_components/ColorTag.tsx
  src/app/custom-keyboard/_components/KeyCapOption.module.scss
  src/app/custom-keyboard/_components/KeyCapOption.tsx
  src/app/custom-keyboard/_components/Keyboard.tsx
  src/app/custom-keyboard/_components/KeyboardViewer.module.scss
  src/app/custom-keyboard/_components/KeyboardViewer.tsx
  src/app/custom-keyboard/_components/Option.tsx
  src/app/custom-keyboard/_components/PriceButton.module.scss
  src/app/custom-keyboard/_components/PriceButton.tsx
  src/app/custom-keyboard/_components/Step.module.scss
  src/app/custom-keyboard/_components/Step.tsx
  src/app/custom-keyboard/_components/StepIcon.module.scss
  src/app/custom-keyboard/_components/StepIcon.tsx
  src/app/custom-keyboard/_components/SwitchHelp.module.scss
  src/app/custom-keyboard/_components/SwitchHelp.tsx
  src/app/custom-keyboard/_components/SwitchOption.module.scss
  src/app/custom-keyboard/_components/SwitchOption.tsx
  src/app/custom-keyboard/customKeyboard.module.scss
  src/app/custom-keyboard/layout.tsx
  src/app/custom-keyboard/page.tsx
  src/app/dw/page.tsx
  src/components/Header/Header.module.scss
  src/components/Header/ShopButton.module.scss
  src/components/Modal/Modal.tsx
  src/constants/keyboardData.ts
  src/context/customKeyboardContext.tsx
  src/middleware.ts
  src/styles/reset.css
  src/types/CustomKeyboardTypes.ts
Labels: 📖 Page, ✨ Component

#56 [Refactor] modal portal과 연동하여 테스트
  .eslintrc.json
  public/svgs/delete.svg
  public/svgs/deleteImage.svg
  public/svgs/deleteTag.svg
  src/app/custom-keyboard/_components/ColorTag.tsx
  src/app/mj/ReviewModalTest.module.scss
  src/app/mj/ReviewModalTest.tsx
  src/app/mj/page.module.scss
  src/app/mj/page.tsx
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/ScrollUpButton/ScrollUpButton.tsx
  src/components/WriteEditModal/ImageInput.module.scss
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.tsx
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/index.ts
  src/constants/writeEditModalType.ts
  src/hooks/useIntersectionObserver.ts
Labels: 🔨 Refactor

#64 [Feat] Button 스토리북 작성
  src/components/Button/Background.stories.tsx
  src/components/Button/Radius.stories.tsx
  src/components/Button/Size.stories.tsx
Labels: 📄 Docs

#65 [Feat] 메인페이지 커스텀 가이드 컴포넌트 구현
  public/images/guide1.png
  public/images/guide2.png
  public/images/guide3.png
  public/images/guide4.png
  public/images/keyduek.png
  src/app/(home)/_components/AnimatedSection.module.scss
  src/app/(home)/_components/AnimatedSection.tsx
  src/app/(home)/_components/CustomGuide.module.scss
  src/app/(home)/_components/CustomGuide.tsx
  src/app/(home)/_components/Guide.module.scss
  src/app/(home)/_components/Guide.tsx
  src/app/(home)/_components/Hero.module.scss
  src/app/(home)/page.tsx
  src/app/(home)/shop/[category]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Breadcrumb/Breadcrumb.module.scss
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/buttons/LikeButton/LikeButton.module.scss
  src/styles/globals/_fonts.scss
Labels: 📖 Page, ✨ Component

#79 [Feat] 커뮤니티 카드 컴포넌트 구현
  public/images/kedeukProfile.png
  public/images/myProfile.jpeg
  public/svgs/camera.svg
  public/svgs/comment.svg
  public/svgs/verticalTripleDot.svg
  src/app/(test)/mj/communityData.ts
  src/app/(test)/mj/page.tsx
  src/app/community/_components/AuthorCard.module.scss
  src/app/community/_components/AuthorCard.tsx
  src/app/community/_components/PostCard.module.scss
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostInteractions.module.scss
  src/app/community/_components/PostInteractions.tsx
  src/app/community/page.module.scss
  src/app/community/page.tsx
  src/components/Buttons/ScrollUpButton/ScrollUpButton.module.scss
  src/components/Buttons/ScrollUpButton/ScrollUpButton.tsx
  src/components/ProfileImage/ProfileImage.module.scss
  src/components/ProfileImage/ProfileImage.tsx
  src/components/WriteEditModal/ImageInput.tsx
  src/components/index.ts
  src/libs/calculateDate.ts
Labels: ✨ Component

#81 [Feat] 마이페이지 - 기본 페이지 구현
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  public/index.ts
  public/svgs/alertIcon.svg
  src/api/securityAPI.ts
  src/api/usersAPI.ts
  src/app/(test)/bk/page.tsx
  src/app/layout.tsx
  src/app/my-info/_components/DeliveryStatus/DeliveryStatus.module.scss
  src/app/my-info/_components/DeliveryStatus/DeliveryStatus.tsx
  src/app/my-info/_components/MyInfoEmptyCase/MyInfoEmptyCase.module.scss
  src/app/my-info/_components/MyInfoEmptyCase/MyInfoEmptyCase.tsx
  src/app/my-info/_components/RecentProducts/RecentProducts.module.scss
  src/app/my-info/_components/RecentProducts/RecentProducts.tsx
  src/app/my-info/_components/SNB/SNB.module.scss
  src/app/my-info/_components/SNB/SNB.tsx
  src/app/my-info/_components/UserProfile/EditProfileModal/EditProfileModal.module.scss
  src/app/my-info/_components/UserProfile/EditProfileModal/EditProfileModal.tsx
  src/app/my-info/_components/UserProfile/UserProfile.module.scss
  src/app/my-info/_components/UserProfile/UserProfile.tsx
  src/app/my-info/_components/index.ts
  src/app/my-info/layout.module.scss
  src/app/my-info/layout.tsx
  src/app/my-info/page.module.scss
  src/app/my-info/page.tsx
  src/app/providers.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Header/HeaderParts/AuthButton.module.scss
  src/components/Header/HeaderParts/CartButton.tsx
  src/components/Header/HeaderParts/LoginButton.tsx
  src/components/Header/HeaderParts/LogoutButton.tsx
  src/components/Header/HeaderParts/SearchBox.module.scss
  src/components/Header/HeaderParts/ShopButton.module.scss
  src/components/Header/HeaderParts/ShopButton.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/InputFiled.module.scss
  src/components/RadioField/RadioField.module.scss
  src/components/RadioField/RadioField.tsx
  src/components/index.ts
  src/components/parts/Input.module.scss
  src/components/parts/Input.tsx
  src/components/parts/Label.tsx
  src/components/parts/Radio.tsx
  src/components/parts/SuffixIcon.module.scss
  src/constants/route.ts
  src/libs/changePhoneNumber.ts
  src/libs/formatBirthDate.ts
  src/libs/formatPhoneNumber.ts
  src/libs/index.ts
  src/libs/manageCookie.ts
  src/libs/unFormatPhoneNumber.ts
  src/styles/globals/_fonts.scss
  src/types/profileType.ts
Labels: 📖 Page, ✨ Component

#84 [Feat] 전체상품 페이지 구현
  next.config.mjs
  src/api/getProductList.ts
  src/app/_components/AnimatedSection.module.scss
  src/app/_components/AnimatedSection.tsx
  src/app/_components/CustomGuide.module.scss
  src/app/_components/CustomGuide.tsx
  src/app/_components/Guide.module.scss
  src/app/_components/Guide.tsx
  src/app/_components/Hero.module.scss
  src/app/_components/Hero.tsx
  src/app/_components/heroItem.ts
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/shop/[category]/page.tsx
  src/app/shop/_components/Category/CategoryMenu.module.scss
  src/app/shop/_components/Category/CategoryMenu.tsx
  src/app/shop/_components/Category/CategoryTitle.module.scss
  src/app/shop/_components/Category/CategoryTitle.tsx
  src/app/shop/_components/Product/ProductList.module.scss
  src/app/shop/_components/Product/ProductList.tsx
  src/app/shop/layout.module.scss
  src/app/shop/layout.tsx
  src/app/shop/page.module.scss
  src/app/shop/page.tsx
  src/app/sign-up/page.tsx
  src/components/Breadcrumb/Breadcrumb.module.scss
  src/components/Header/HeaderParts/ShopButton.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Products/ProductItem.module.scss
  src/components/Products/ProductItem.tsx
  src/libs/calculatePage.ts
  src/types/ProductItem.ts
Labels: 📖 Page, 📬 API, 🥰 Accessibility, ✨ Component

#83 [Feat] 커뮤니티 상세 페이지 모달창 및 레이아웃 구현
  .gitignore
  public/svgs/plus.svg
  src/app/(test)/mj/communityData.ts
  src/app/community/_components/AuthorCard.module.scss
  src/app/community/_components/AuthorCard.tsx
  src/app/community/_components/Comment.module.scss
  src/app/community/_components/Comment.tsx
  src/app/community/_components/PostCard.module.scss
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostCardDetailModal.module.scss
  src/app/community/_components/PostCardDetailModal.tsx
  src/app/community/_components/PostInteractions.module.scss
  src/app/community/_components/PostInteractions.tsx
  src/app/community/_components/WritePostButton.module.scss
  src/app/community/_components/WritePostButton.tsx
  src/app/community/page.module.scss
  src/app/community/page.tsx
  src/components/Buttons/ScrollUpButton/ScrollUpButton.module.scss
  src/components/WriteEditModal/ImageInput.module.scss
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.module.scss
  src/components/WriteEditModal/KeyboardInfoBox.tsx
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/libs/addEnterKeyEvent.ts
  src/libs/calculateDate.ts
  src/libs/formatDateToString.ts
  src/styles/globals/_fonts.scss
Labels: 📖 Page, ✨ Component

#94 [Feat] 알림창 공통 컴포넌트 구현
  public/index.ts
  public/svgs/warnCircle.svg
  src/app/(test)/dw/page.tsx
  src/components/Dialog/Dialog.module.scss
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogIcon.module.scss
  src/components/Dialog/DialogIcon.tsx
Labels: ✨ Component

#92 [Feat] 커스텀 키보드 페이지 api 연결
  .gitignore
  package-lock.json
  package.json
  public/images/keydeuk.png
  public/images/optionProductMock.png
  public/index.ts
  src/api/customKeyboardAPI.ts
  src/app/(test)/mj/communityData.ts
  src/app/_components/CustomGuide.tsx
  src/app/_components/heroItem.ts
  src/app/community/_components/AuthorCard.tsx
  src/app/community/_components/PostCardDetailModal.tsx
  src/app/community/_components/PostInteractions.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/custom-keyboard/_components/canvas/KeyboardViewer.tsx
  src/app/custom-keyboard/_components/canvas/Step.tsx
  src/app/custom-keyboard/_components/canvas/parts/CanvasLoading.tsx
  src/app/custom-keyboard/_components/canvas/parts/Keyboard.tsx
  src/app/custom-keyboard/_components/canvas/parts/StepIcon.tsx
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/app/custom-keyboard/_components/navigator/OptionProductModal.tsx
  src/app/custom-keyboard/_components/navigator/TotalCostWithNavigation.tsx
  src/app/custom-keyboard/_components/navigator/parts/CartModalOptionCard.tsx
  src/app/custom-keyboard/_components/navigator/parts/CartModalToast.tsx
  src/app/custom-keyboard/_components/navigator/parts/OptionProductCard.module.scss
  src/app/custom-keyboard/_components/navigator/parts/OptionProductCard.tsx
  src/app/custom-keyboard/_components/navigator/parts/TooltipColor.tsx
  src/app/custom-keyboard/_components/option/BoardOption.module.scss
  src/app/custom-keyboard/_components/option/BoardOption.tsx
  src/app/custom-keyboard/_components/option/KeyCapOption.module.scss
  src/app/custom-keyboard/_components/option/KeyCapOption.tsx
  src/app/custom-keyboard/_components/option/Option.tsx
  src/app/custom-keyboard/_components/option/SwitchHelpModal.module.scss
  src/app/custom-keyboard/_components/option/SwitchHelpModal.tsx
  src/app/custom-keyboard/_components/option/SwitchOption.module.scss
  src/app/custom-keyboard/_components/option/SwitchOption.tsx
  src/app/custom-keyboard/_components/option/parts/ColorTag.tsx
  src/app/custom-keyboard/layout.tsx
  src/app/custom-keyboard/page.tsx
  src/app/layout.tsx
  src/components/Buttons/Button/Button.module.scss
  src/components/Buttons/LikeButton/LikeButton.tsx
  src/components/Buttons/ScrollUpButton/ScrollUpButton.tsx
  src/components/Header/HeaderParts/CartButton.tsx
  src/components/Pagination/Pagination.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/components/Rating/Rating.tsx
  src/components/WriteEditModal/ImageInput.tsx
  src/context/FocusKeyContext.tsx
  src/context/KeyboardDataContext.tsx
  src/context/StepContext.tsx
  src/context/customKeyboardContext.tsx
  src/context/index.ts
  src/hooks/useCanvasCaptrue.ts
  src/libs/getBlurImage.ts
  src/types/CustomKeyboardTypes.ts
Labels: 📖 Page, 📬 API, 🎨 Style, ✨ Component

#89 [Feat] 상품 상세 상단 부분 UI 구현
  public/index.ts
  public/svgs/delete.svg
  public/svgs/minusCircle.svg
  public/svgs/plusCircle.svg
  src/api/cartAPI.ts
  src/api/productAPI.ts
  src/app/(test)/yj/detail/page.tsx
  src/app/community/_components/PostInteractions.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionContainer.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
  src/app/shop/[category]/[productId]/_components/Product/ProductDetail.module.scss
  src/app/shop/[category]/[productId]/_components/Product/ProductDetail.tsx
  src/app/shop/[category]/[productId]/_components/Product/QuantitySelector.tsx
  src/app/shop/[category]/[productId]/_components/Product/Thumbnail.module.scss
  src/app/shop/[category]/[productId]/_components/Product/Thumbnail.tsx
  src/app/shop/[category]/[productId]/page.tsx
  src/components/Buttons/LikeButton/LikeButton.module.scss
  src/components/Buttons/LikeButton/LikeButton.tsx
  src/components/Dialog/DialogIcon.tsx
  src/components/index.ts
  src/types/ProductTypes.ts
Labels: 📖 Page, 📬 API, ✨ Component

#99 [Feat] 마이페이지 배송지관리 페이지 제작
  next.config.mjs
  package-lock.json
  package.json
  public/svgs/alertIcon.svg
  public/svgs/crossCircle.svg
  src/api/shippingAPI.ts
  src/api/usersAPI.ts
  src/app/(test)/bk/page.tsx
  src/app/custom-keyboard/_components/option/Option.tsx
  src/app/custom-keyboard/_components/option/SwitchOption.tsx
  src/app/layout.tsx
  src/app/my-info/(account)/addresses/_components/AddAddresseModal/AddAddressModal.module.scss
  src/app/my-info/(account)/addresses/_components/AddAddresseModal/AddAddressModal.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/Address/Address.module.scss
  src/app/my-info/(account)/addresses/_components/Addresses/Address/Address.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/Addresses.module.scss
  src/app/my-info/(account)/addresses/_components/Addresses/Addresses.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/AddressesEmptyCase/AddressesEmptyCase.module.scss
  src/app/my-info/(account)/addresses/_components/Addresses/AddressesEmptyCase/AddressesEmptyCase.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/index.ts
  src/app/my-info/(account)/addresses/_components/AddressesHeader/AddressesHeader.module.scss
  src/app/my-info/(account)/addresses/_components/AddressesHeader/AddressesHeader.tsx
  src/app/my-info/(account)/addresses/_components/index.ts
  src/app/my-info/(account)/addresses/layout.module.scss
  src/app/my-info/(account)/addresses/layout.tsx
  src/app/my-info/(account)/addresses/page.tsx
  src/app/my-info/_components/DeliveryStatus/DeliveryStatus.module.scss
  src/app/my-info/_components/DeliveryStatus/DeliveryStatus.tsx
  src/app/my-info/_components/MyInfoEmptyCase/MyInfoEmptyCase.module.scss
  src/app/my-info/_components/MyInfoEmptyCase/MyInfoEmptyCase.tsx
  src/app/my-info/_components/RecentProducts/RecentProducts.tsx
  src/app/my-info/_components/SNB/SNB.module.scss
  src/app/my-info/_components/SNB/SNB.tsx
  src/app/my-info/_components/UserProfile/EditProfileModal/EditProfileModal.tsx
  src/app/my-info/_components/UserProfile/UserProfile.tsx
  src/app/my-info/layout.module.scss
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Header/HeaderParts/ShopButton.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/InputFiled.module.scss
  src/components/ProfileImage/ProfileImage.tsx
  src/components/RadioField/RadioField.tsx
  src/components/parts/Input.tsx
  src/components/parts/SuffixIcon.tsx
  src/libs/changePhoneNumber.ts
  src/libs/formatNumber.ts
  src/libs/index.ts
  src/libs/isNumberAllowedKey.ts
  src/libs/unFormatNumber.ts
  src/styles/globals/_colors.scss
  src/types/shippingType.ts
  src/types/userType.ts
Labels: 📖 Page, 📬 API, ✨ Component

#98 [Feat] 로그인 & 회원가입 구현
  public/.index.ts.swp
  public/index.ts
  public/svgs/gitHub.svg
  public/svgs/google.svg
  public/svgs/kakaotalk.svg
  src/api/authAPI.ts
  src/app/(auth)/sign-in/_component/SignInModal.tsx
  src/app/(auth)/sign-in/_component/SigninModal.module.scss
  src/app/(auth)/sign-in/page.module.scss
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/_component/SignupForm.module.scss
  src/app/(auth)/sign-up/_component/SignupForm.tsx
  src/app/(auth)/sign-up/page.module.scss
  src/app/(auth)/sign-up/page.tsx
  src/app/(test)/mj/page.tsx
  src/app/layout.tsx
  src/app/sign-up/page.tsx
  src/components/RadioField/RadioField.module.scss
  src/constants/signUpConstants.ts
  src/styles/toast/toastAnimation.scss
  src/styles/toast/toastContainer.scss
  src/types/authTypes.ts
Labels: 📖 Page, 📬 API, ✨ Component

#96 [Feat] date picker 구현
  public/index.ts
  public/svgs/calendar.svg
  src/app/(test)/mj/page.module.scss
  src/app/(test)/mj/page.tsx
  src/app/(test)/mj/test/DatePickerTest.tsx
  src/app/(test)/mj/test/ReviewModalTest.module.scss
  src/app/(test)/mj/test/ReviewModalTest.tsx
  src/components/Buttons/LikeButton/LikeButton.module.scss
  src/components/Buttons/LikeButton/LikeButton.tsx
  src/components/DatePicker/Calendar.module.scss
  src/components/DatePicker/Calendar.tsx
  src/components/DatePicker/DatePicker.module.scss
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/Days.tsx
  src/types/DatePickerTypes.ts
Labels: ✨ Component

#103 [Fix] header position & input style 수정
  package-lock.json
  package.json
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/_component/SignupForm.module.scss
  src/app/(auth)/sign-up/_component/SignupForm.tsx
  src/app/(test)/bk/page.tsx
  src/app/layout.tsx
  src/app/my-info/(account)/addresses/layout.tsx
  src/app/my-info/(account)/reviews/layout.module.scss
  src/app/my-info/(account)/reviews/layout.tsx
  src/app/my-info/(account)/reviews/page.tsx
  src/app/my-info/(account)/wishlist/layout.module.scss
  src/app/my-info/(account)/wishlist/layout.tsx
  src/app/my-info/(account)/wishlist/page.tsx
  src/app/my-info/_components/UserProfile/EditProfileModal/EditProfileModal.tsx
  src/app/my-info/layout.tsx
  src/app/providers.tsx
  src/components/DatePicker/Calendar.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Header/HeaderParts/CartButton.module.scss
  src/components/Header/HeaderParts/CartButton.tsx
  src/components/Header/HeaderParts/LoginButton.tsx
  src/components/Header/HeaderParts/LogoutButton.tsx
  src/components/RadioField/RadioField.tsx
  src/components/RadioField/index.stories.tsx
  src/components/SignInModal/SignInModal.tsx
  src/components/SignInModal/SigninModal.module.scss
  src/components/index.ts
  src/components/parts/Input.module.scss
  src/components/parts/Input.tsx
  src/components/parts/Radio.module.scss
  src/components/parts/Radio.tsx
  src/constants/dropdownOptions.ts
  src/constants/signUpConstants.ts
  src/libs/formatBirthDate.ts
Labels: 🐞 Fix, 🔨 Refactor

#105 [Feat] 상품 상세 탭 메뉴, 들어가는 내용 구현
  next.config.mjs
  public/index.ts
  public/svgs/noReview.svg
  public/svgs/speechBubble.svg
  src/api/productAPI.ts
  src/api/productReviewAPI.ts
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
  src/app/shop/[category]/[productId]/_components/Product/ProductDetail.module.scss
  src/app/shop/[category]/[productId]/_components/Product/Thumbnail.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/DetailImage.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/DetailImage.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/DetailTab.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/DetailTab.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/ReturnExchangeInfo.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/ReturnExchangeInfo.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/KeywordRatio.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/KeywordRatios.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ProductReviewList.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ProductReviewList.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewImageList.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewImageList.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewPreview.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewPreview.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ScoreGraph.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ScoreGraph.tsx
  src/app/shop/[category]/[productId]/page.tsx
  src/app/shop/layout.module.scss
  src/components/ReviewItem/RenderImages.tsx
  src/components/ReviewItem/ReviewItem.module.scss
  src/components/ReviewItem/ReviewItem.tsx
  src/components/parts/Radio.tsx
  src/constants/blurImage.ts
  src/constants/dropdownOptions.ts
  src/constants/reviewKeyword.ts
  src/hooks/useIntersectionObserver.ts
  src/libs/getMaxKey.ts
  src/styles/globals/_fonts.scss
  src/types/ProductReviewTypes.ts
Labels: ⚙ Setting, 📖 Page, ✨ Component

#111 [Feat] Footer 구현
  public/index.ts
  public/svgs/gitHubRectangle.svg
  public/svgs/logo.svg
  src/app/(test)/dw/page.tsx
  src/app/layout.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
  src/components/Footer/HoverLinkIcon.module.scss
  src/components/Footer/HoverLinkIcon.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/index.ts
  src/constants/route.ts
  src/styles/globals/_colors.scss
Labels: ✨ Component

#117 [Fix] 로그인 모달 오류 수정
  public/index.ts
  public/svgs/upArrow.svg
  src/app/(auth)/sign-in/page.tsx
  src/app/Providers.module.scss
  src/app/providers.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
  src/components/Buttons/ScrollUpButton/ScrollUpButton.module.scss
  src/components/Buttons/ScrollUpButton/ScrollUpButton.tsx
  src/components/Header/Header.tsx
  src/components/SignInModal/SignInModal.tsx
  src/hooks/useIntersectionObserver.ts
Labels: 🐞 Fix, ✨ Component

#108 [Feat] 메인 리스트 구현
  package-lock.json
  package.json
  public/images/banner1.png
  public/images/banner2.png
  public/index.ts
  public/svgs/404.svg
  src/api/productAPI.ts
  src/app/(test)/ye/page.module.scss
  src/app/(test)/ye/page.tsx
  src/app/_components/Banner/Banner.module.scss
  src/app/_components/Banner/Banner.tsx
  src/app/_components/CustomGuide.module.scss
  src/app/_components/Guide/AnimatedSection.module.scss
  src/app/_components/Guide/AnimatedSection.tsx
  src/app/_components/Guide/CustomGuide.module.scss
  src/app/_components/Guide/CustomGuide.tsx
  src/app/_components/Guide/Guide.module.scss
  src/app/_components/Guide/Guide.tsx
  src/app/_components/Hero/Hero.module.scss
  src/app/_components/Hero/Hero.tsx
  src/app/_components/Hero/heroItem.ts
  src/app/_components/KeydeukBest/KeydeukBest.module.scss
  src/app/_components/KeydeukBest/KeydeukBest.tsx
  src/app/_components/KeydeukPick/KeydeukPick.module.scss
  src/app/_components/KeydeukPick/KeydeukPick.tsx
  src/app/_components/TextTicker/TextTickerSection.module.scss
  src/app/_components/TextTicker/TextTickerSection.tsx
  src/app/not-found.module.scss
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/shop/[category]/_components/TitleWrap/Filter.tsx
  src/app/shop/[category]/_components/TitleWrap/TitleWrap.tsx
  src/app/shop/[category]/page.module.scss
  src/app/shop/[category]/page.tsx
  src/app/shop/_components/Product/ProductList.tsx
  src/app/shop/layout.module.scss
  src/app/shop/layout.tsx
  src/app/shop/page.module.scss
  src/app/shop/page.tsx
  src/components/Breadcrumb/Breadcrumb.module.scss
  src/components/Pagination/Pagination.tsx
  src/components/Products/ProductItem.module.scss
  src/components/Products/ProductItem.tsx
  src/constants/dropdownOptions.ts
  src/constants/product.ts
  src/constants/queryKey.ts
  src/styles/globals/_fonts.scss
  src/styles/globals/_mixin.scss
  src/types/ProductItem.ts
Labels: 📖 Page, 📬 API, ✨ Component

#112 [Feat] 마이페이지 API 연동
  src/api/communityAPI.ts
  src/app/(test)/mj/OrderListModatTest.tsx
  src/app/(test)/mj/communityData.ts
  src/app/(test)/mj/customData.ts
  src/app/(test)/mj/page.tsx
  src/app/(test)/mj/test/ReviewModalTest.tsx
  src/app/community/_components/AuthorCard.module.scss
  src/app/community/_components/AuthorCard.tsx
  src/app/community/_components/Comment.module.scss
  src/app/community/_components/Comment.tsx
  src/app/community/_components/OrderListModal.module.scss
  src/app/community/_components/OrderListModal.tsx
  src/app/community/_components/PostCard.module.scss
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostCardDetailModal.module.scss
  src/app/community/_components/PostCardDetailModal.tsx
  src/app/community/_components/PostCardList.module.scss
  src/app/community/_components/PostCardList.tsx
  src/app/community/_components/PostInteractions.tsx
  src/app/community/_components/SortDropdown.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/community/page.module.scss
  src/app/community/page.tsx
  src/app/my-info/(account)/my-posts/_components/MyPostCardList.module.scss
  src/app/my-info/(account)/my-posts/_components/MyPostCardList.tsx
  src/app/my-info/(account)/my-posts/_components/SortDropdown.tsx
  src/app/my-info/(account)/my-posts/page.module.scss
  src/app/my-info/(account)/my-posts/page.tsx
  src/app/my-info/_components/SNB/SNB.tsx
  src/components/PopOver/PopOver.module.scss
  src/components/PopOver/PopOver.tsx
  src/components/WriteEditModal/FeedbackToggle.module.scss
  src/components/WriteEditModal/FeedbackToggle.tsx
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/KeyboardInfoBox.module.scss
  src/components/WriteEditModal/KeyboardInfoBox.tsx
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/components/WriteEditModal/WriteEditModal.tsx
  src/components/index.ts
  src/constants/dropdownOptions.ts
  src/types/CommunityTypes.ts
Labels: 📖 Page, 📬 API, ✨ Component

#120 [Fix] 커뮤니티 및 마이페이지 내 게시글 수정
  src/app/(test)/mj/test/ReviewModalTest.tsx
  src/app/community/_components/OrderListModal.tsx
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostCardDetailModal.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/my-info/(account)/my-posts/page.module.scss
  src/components/CustomOption/OptionWrapper.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/InputFiled.module.scss
  src/components/ProfileImage/ProfileImage.tsx
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/WriteEditModal.tsx
Labels: 🐞 Fix

#119 [Feat] 찜, 리뷰 좋아요, 공유 버튼, 최근 본 상품 구현
  public/index.ts
  public/svgs/link.svg
  public/svgs/minusCircle.svg
  public/svgs/plusCircle.svg
  public/svgs/share.svg
  src/api/communityAPI.ts
  src/api/likesAPI.ts
  src/api/productAPI.ts
  src/api/productReviewAPI.ts
  src/app/_components/Hero/Hero.module.scss
  src/app/_components/Hero/Hero.tsx
  src/app/_components/KeydeukPick/KeydeukPick.tsx
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostCardDetailModal.tsx
  src/app/community/_components/PostInteractions.module.scss
  src/app/community/_components/PostInteractions.tsx
  src/app/custom-keyboard/_components/canvas/parts/StepIcon.module.scss
  src/app/my-info/(account)/addresses/_components/AddressesHeader/AddressesHeader.module.scss
  src/app/my-info/_components/RecentProducts/RecentProducts.module.scss
  src/app/my-info/_components/RecentProducts/RecentProducts.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionContainer.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
  src/app/shop/[category]/[productId]/_components/Product/ProductDetail.module.scss
  src/app/shop/[category]/[productId]/_components/Product/ProductDetail.tsx
  src/app/shop/[category]/[productId]/_components/Product/QuantitySelector.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/DetailTab.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/KeywordRatios.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ProductReviewList.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ProductReviewList.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewImageList.module.scss
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewImageList.tsx
  src/app/shop/[category]/[productId]/_components/TabContents/Review/ReviewPreview.tsx
  src/app/shop/[category]/_components/TitleWrap/Filter.module.scss
  src/components/Buttons/HeartButton/HeartButton.module.scss
  src/components/Buttons/HeartButton/HeartButton.tsx
  src/components/Buttons/LikeButton/LikeButton.tsx
  src/components/Buttons/ReviewLikeButton/ReviewLikeButton.module.scss
  src/components/Buttons/ReviewLikeButton/ReviewLikeButton.tsx
  src/components/Buttons/ShareButton/ShareBox.tsx
  src/components/Buttons/ShareButton/ShareButton.module.scss
  src/components/Buttons/ShareButton/ShareButton.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Products/ProductItem.tsx
  src/components/ReviewItem/ReviewItem.module.scss
  src/components/ReviewItem/ReviewItem.tsx
  src/components/SignInModal/SigninModal.module.scss
  src/components/index.ts
  src/styles/globals/_fonts.scss
  src/types/ProductTypes.ts
Labels: ✨ Component

#123 [Refactor] 커뮤니티 레이아웃 css 수정 및 상품 정보 컴포넌트 적용
  public/svgs/comment.svg
  src/api/likesAPI.ts
  src/app/community/_components/OrderListModal.module.scss
  src/app/community/_components/OrderListModal.tsx
  src/app/community/_components/PostCardList.module.scss
  src/app/community/_components/PostInteractions.module.scss
  src/app/community/_components/PostInteractions.tsx
  src/app/community/page.module.scss
  src/components/Buttons/ReviewLikeButton/ReviewLikeButton.module.scss
  src/styles/toast/toastAnimation.scss
  src/types/CommunityTypes.ts
Labels: 🐞 Fix, 🔨 Refactor

#122 [Fix] 커스텀 키보드 페이지 수정
  public/index.ts
  public/svgs/canvasLoading.svg
  src/app/community/_components/WritePostButton.tsx
  src/app/custom-keyboard/EventProvider.tsx
  src/app/custom-keyboard/_components/canvas/KeyboardViewer.tsx
  src/app/custom-keyboard/_components/canvas/parts/CanvasLoading.module.scss
  src/app/custom-keyboard/_components/canvas/parts/CanvasLoading.tsx
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/app/custom-keyboard/_components/navigator/OptionProductModal.module.scss
  src/app/custom-keyboard/_components/navigator/OptionProductModal.tsx
  src/app/custom-keyboard/_components/navigator/TotalCostWithNavigation.module.scss
  src/app/custom-keyboard/_components/navigator/TotalCostWithNavigation.tsx
  src/app/custom-keyboard/_components/navigator/parts/CartModalOptionCard.module.scss
  src/app/custom-keyboard/_components/navigator/parts/CartModalOptionCard.tsx
  src/app/custom-keyboard/_components/navigator/parts/CartModalToast.module.scss
  src/app/custom-keyboard/_components/navigator/parts/CartModalToast.tsx
  src/app/custom-keyboard/_components/navigator/parts/OptionProductCard.module.scss
  src/app/custom-keyboard/_components/option/BoardOption.module.scss
  src/app/custom-keyboard/_components/option/BoardOption.tsx
  src/app/custom-keyboard/_components/option/KeyCapOption.module.scss
  src/app/custom-keyboard/_components/option/KeyCapOption.tsx
  src/app/custom-keyboard/_components/option/SwitchOption.module.scss
  src/app/custom-keyboard/_components/option/SwitchOption.tsx
  src/app/custom-keyboard/customKeyboard.module.scss
  src/app/custom-keyboard/layout.tsx
  src/app/custom-keyboard/page.tsx
  src/app/loading.tsx
  src/app/my-info/(account)/cart/_components/CartCard.module.scss
  src/app/my-info/(account)/cart/_components/CartCard.tsx
  src/app/my-info/(account)/cart/_components/DeleteButton.module.scss
  src/app/my-info/(account)/cart/_components/DeleteButton.tsx
  src/app/my-info/(account)/cart/_components/OptionEditModal.module.scss
  src/app/my-info/(account)/cart/_components/OptionEditModal.tsx
  src/app/my-info/(account)/cart/_components/PurchaseButton.module.scss
  src/app/my-info/(account)/cart/_components/PurchaseButton.tsx
  src/app/my-info/(account)/cart/_components/TotalCheckBox.tsx
  src/app/my-info/(account)/cart/page.module.scss
  src/components/Buttons/Button/Button.module.scss
  src/components/Buttons/Button/Button.tsx
  src/components/LogoLoading/LogoLoading.module.scss
  src/components/LogoLoading/LogoLoading.tsx
  src/context/CartDataContext.tsx
  src/context/KeyboardDataContext.tsx
  src/hooks/useOutsideClick.ts
Labels: 📖 Page, 🐞 Fix, ✨ Component

#125 [Fix] 데이터 null 처리
  src/app/community/_components/Comment.tsx
Labels: 🐞 Fix

#127 [Fix] 커스텀 키보드 장바구니 수정 반영
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/app/not-found.module.scss
Labels: 🐞 Fix

#130 [Feat] 장바구니 일반 상품 클릭 시 페이지 이동
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/app/my-info/(account)/cart/_components/CartCard.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
  src/components/SignInModal/SignInModal.tsx
  src/styles/globals/_fonts.scss
Labels: 📖 Page

#133 [Fix] 커스텀 키보드 로그인 모달 새로고침 수정
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/app/custom-keyboard/_components/navigator/TotalCostWithNavigation.tsx
  src/app/my-info/(account)/cart/_components/DeleteButton.tsx
  src/components/LogoLoading/LogoLoading.module.scss
Labels: 📖 Page, 🐞 Fix

#131 [Fix] date picker 수정
  src/app/community/_components/OrderListModal.module.scss
  src/app/community/_components/OrderListModal.tsx
  src/app/community/_components/PostInteractions.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/components/DatePicker/DatePicker.module.scss
  src/components/DatePicker/DatePicker.tsx
  src/components/ItemOverview/ItemOverview.module.scss
  src/components/ItemOverview/ItemOverview.tsx
  src/components/LogoLoading/LogoLoading.module.scss
Labels: 🐞 Fix

#135 [Feat] payment UI 기능 추가
  src/api/orderAPI.ts
  src/app/(payment)/payment/_components/Checkout/CheckoutForm/CheckoutForm.module.scss
  src/app/(payment)/payment/_components/Checkout/CheckoutForm/CheckoutForm.tsx
  src/app/(payment)/payment/layout.tsx
  src/app/my-info/(account)/addresses/_components/AddAddresseModal/AddAddressModal.module.scss
  src/app/my-info/(account)/addresses/_components/AddAddresseModal/AddAddressModal.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/Address/Address.tsx
  src/app/my-info/(account)/addresses/_components/AddressesHeader/AddressesHeader.tsx
  src/app/my-info/(account)/orders/_components/Orders/OrderItemList/OrderItem/OrderItem.tsx
  src/app/my-info/(account)/orders/_components/Orders/OrderItemList/OrderItem/OrderItemButton/OrderItemButton.tsx
  src/app/my-info/(account)/orders/_components/Orders/OrderItemList/OrderItemList.tsx
  src/app/my-info/(account)/orders/_components/Orders/Orders.tsx
  src/app/my-info/_components/DeliveryStatus/DeliveryStatus.tsx
  src/app/my-info/_components/SNB/SNB.tsx
  src/app/my-info/_components/UserProfile/EditProfileModal/EditProfileModal.tsx
  src/app/providers.tsx
  src/components/Buttons/Button/Button.module.scss
  src/components/ItemOverview/ItemOverview.tsx
  src/libs/getOrderStatusDescriptions.ts
  src/types/OrderTypes.ts
  src/types/orderType.ts
  src/types/paymentTypes.ts
Labels: ✨ Component
