Repository Quad8/quad8-front, pull requests merged in 2024-08, with the labels that each got.

#160 [Feat] 다른 유저 프로필 보기
  src/api/usersAPI.ts
  src/app/(test)/mj/page.tsx
  src/app/(test)/mj/test/ImageZoomText.tsx
  src/app/community/_components/AuthorCard.module.scss
  src/app/community/_components/AuthorCard.tsx
  src/app/community/_components/Comment.module.scss
  src/app/community/_components/Comment.tsx
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostCardDetailModal/ErrorFallbackDetailModal.tsx
  src/app/community/_components/PostCardDetailModal/PostCardDetailModal.module.scss
  src/app/community/_components/PostCardDetailModal/PostCardDetailModal.tsx
  src/app/community/_components/SortDropdown.module.scss
  src/app/community/_components/SortDropdown.tsx
  src/app/community/_components/UserProfileCard.module.scss
  src/app/community/_components/UserProfileCard.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/community/layout.module.scss
  src/app/community/layout.tsx
  src/app/my-info/(account)/my-posts/_components/MyPostsEmptyCase.module.scss
  src/app/my-info/(account)/my-posts/_components/MyPostsEmptyCase.tsx
  src/app/my-info/(account)/my-posts/page.tsx
  src/components/Buttons/HeartButton/HeartButton.tsx
  src/components/ImageZoom/ImageZoom.module.scss
  src/components/ImageZoom/ImageZoom.tsx
  src/components/ImageZoom/ZoomView.module.scss
  src/components/ImageZoom/ZoomView.tsx
  src/components/ModalSkeleton/ModalSkeleton.module.scss
  src/components/ModalSkeleton/ModalSkeleton.tsx
  src/components/PopOver/PopOver.module.scss
  src/components/PopOver/PopOver.tsx
  src/components/ProfileImage/ProfileImage.module.scss
  src/components/index.ts
  src/libs/communityPopOverOption.ts
  src/types/CommunityTypes.ts
  src/types/userType.ts
Labels: ✨ Component

#166 [Feat] 커뮤니티 알림 구현
  .eslintrc.json
  package-lock.json
  package.json
  public/images/error.png
  public/index.ts
  public/svgs/commentAlarm.svg
  public/svgs/couponAlarm.svg
  public/svgs/notification.svg
  public/svgs/orderAlarm.svg
  src/api/alarmAPI.ts
  src/app/(auth)/sign-in/page.tsx
  src/app/community/_components/PostCard.tsx
  src/app/community/_components/PostCardDetailModal/PostCardDetailModal.tsx
  src/app/custom-keyboard/_components/canvas/Step.module.scss
  src/app/custom-keyboard/_components/navigator/CartModal.tsx
  src/app/custom-keyboard/_components/navigator/parts/CartModalOptionCard.tsx
  src/app/custom-keyboard/_components/navigator/parts/OptionProductCard.tsx
  src/app/custom-keyboard/_components/option/SwitchOption.module.scss
  src/app/custom-keyboard/_components/option/SwitchOption.tsx
  src/app/layout.tsx
  src/app/my-info/(account)/cart/_components/CartCard.tsx
  src/app/my-info/(account)/cart/_components/OptionEditModal.module.scss
  src/app/my-info/(account)/cart/_components/OptionEditModal.tsx
  src/app/my-info/(account)/wishlist/_components/AddCartModal.module.scss
  src/app/my-info/(account)/wishlist/_components/AddCartModal.tsx
  src/app/providers.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionContainer.tsx
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
  src/app/shop/[category]/[productId]/_components/Product/ProductDetail.module.scss
  src/components/CountInput/CountInput.module.scss
  src/components/CountInput/CountInput.tsx
  src/components/CustomImage/CustomImage.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Header/HeaderParts/AuthButton.module.scss
  src/components/Header/HeaderParts/CartButton.tsx
  src/components/Header/HeaderParts/LoginButton.tsx
  src/components/Header/HeaderParts/LogoutButton.tsx
  src/components/Header/HeaderParts/NotificationButton.module.scss
  src/components/Header/HeaderParts/NotificationButton.tsx
  src/components/Header/HeaderParts/NotificationCard.module.scss
  src/components/Header/HeaderParts/NotificationCard.tsx
  src/components/Header/HeaderParts/NotificationCardIcon.module.scss
  src/components/Header/HeaderParts/NotificationCardIcon.tsx
  src/components/Header/HeaderParts/SearchButton.module.scss
  src/components/Header/HeaderParts/ShopButton.module.scss
  src/components/Header/HeaderParts/ShopButton.tsx
  src/components/Header/HeaderParts/index.ts
  src/components/SignInModal/SignInModal.tsx
  src/components/index.ts
  src/hooks/useEventSource.ts
  src/libs/checkValidImage.ts
  src/libs/getCurrentAlarm.ts
  src/styles/globals/_fonts.scss
  src/styles/toast/toastAnimation.scss
  src/styles/toast/toastContainer.scss
  src/types/alarmType.ts
Labels: 📬 API, ✨ Component

#167 [Feat] 마이페이지에서 리뷰 수정, 삭제 모달 연결
  src/api/productReviewAPI.ts
  src/app/(test)/mj/test/ReviewModalTest.tsx
  src/app/my-info/(account)/reviews/_components/MyReviewList.tsx
  src/app/my-info/(account)/reviews/_components/MyReviewProduct.module.scss
  src/app/my-info/(account)/reviews/_components/MyReviewProduct.tsx
  src/components/WriteEditModal/ImageInput.tsx
  src/components/WriteEditModal/WriteEditModal.tsx
  src/types/productReviewType.ts
Labels: ✨ Component

#169 [Feat] 쿠폰 페이지 구현
  public/index.ts
  public/svgs/keydeukBlueIcon.svg
  src/api/couponAPI.ts
  src/app/community/_components/AuthorCard.tsx
  src/app/community/_components/Comment.tsx
  src/app/community/_components/PostCardDetailModal/PostCardDetailModal.tsx
  src/app/community/_components/PostCardList.tsx
  src/app/community/_components/UserProfileCard.module.scss
  src/app/community/_components/UserProfileCard.tsx
  src/app/community/page.tsx
  src/app/my-info/(account)/coupons/_components/Coupon.module.scss
  src/app/my-info/(account)/coupons/_components/Coupon.tsx
  src/app/my-info/(account)/coupons/_components/CouponList.module.scss
  src/app/my-info/(account)/coupons/_components/CouponList.tsx
  src/app/my-info/(account)/coupons/page.module.scss
  src/app/my-info/(account)/coupons/page.tsx
  src/app/my-info/(account)/my-posts/_components/MyPostsEmptyCase.tsx
  src/app/my-info/(account)/my-posts/page.tsx
  src/app/my-info/(account)/orders/_components/Orders/OrderItemList/OrderItemList.tsx
  src/app/my-info/(account)/reviews/_components/MyReviewProduct.tsx
  src/app/my-info/_components/SNB/SNB.tsx
  src/components/Buttons/HeartButton/HeartButton.module.scss
  src/components/DatePicker/Calendar.module.scss
  src/components/DatePicker/Calendar.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/ImageZoom/ImageZoom.module.scss
  src/components/ImageZoom/ImageZoom.tsx
  src/components/ImageZoom/ZoomView.tsx
  src/components/ReviewItem/ReviewItem.tsx
  src/constants/route.ts
  src/libs/formatDateToString.ts
  src/libs/formatNumberToPrice.ts
  src/types/communityType.ts
  src/types/couponType.ts
  src/types/zoomViewType.ts
Labels: 📖 Page

#176 [Fix] 상품 정보 옵션 컴포넌트 수정
  src/app/my-info/(account)/cart/_components/CartCard.module.scss
  src/app/my-info/(account)/cart/_components/CartCard.tsx
  src/app/my-info/(account)/wishlist/_components/WishCheckBox.module.scss
  src/app/my-info/(account)/wishlist/_components/WishItem.module.scss
  src/app/my-info/(account)/wishlist/_components/WishItem.tsx
  src/app/payment/(paymentResult)/success/_components/CheckoutCompleted.tsx
  src/app/payment/_components/CheckoutForm/CheckoutForm.tsx
  src/components/CustomOption/FirstOption.tsx
  src/components/ItemOverview/ItemOverview.module.scss
  src/components/ItemOverview/ItemOverview.tsx
  src/components/ItemOverview/ItemWrapper.module.scss
  src/components/ItemOverview/ItemWrapper.tsx
  src/components/ItemOverview/ShopOption.module.scss
  src/components/ItemOverview/ShopOption.tsx
  src/components/Skeleton/Skeleton.module.scss
  src/components/Skeleton/Skeleton.tsx
  src/components/index.ts
  src/libs/convertProductCategory.ts
  src/libs/formatCartDataToItemOverview.ts
  src/types/KakaoType.ts
  src/types/SearchType.ts
  src/types/cartType.ts
  src/types/orderType.ts
  src/types/productType.ts
  src/types/searchType.ts
Labels: 🐞 Fix, 📬 API

#174 [Feat] 이벤트페이지
  package-lock.json
  public/images/backconfetti.png
  public/images/couponDown.png
  public/images/delivery.png
  public/images/eventTop.png
  public/images/point.png
  public/images/roulette.png
  public/index.ts
  public/svgs/clover.svg
  public/svgs/free.svg
  src/api/couponAPI.ts
  src/api/productAPI.ts
  src/app/(test)/dw/page.tsx
  src/app/custom-keyboard/_components/navigator/TotalCostWithNavigation.tsx
  src/app/event/_components/BenefitDelivery.module.scss
  src/app/event/_components/BenefitDelivery.tsx
  src/app/event/_components/BenefitJoin.module.scss
  src/app/event/_components/BenefitJoin.tsx
  src/app/event/_components/BenefitRoulette.module.scss
  src/app/event/_components/BenefitRoulette.tsx
  src/app/event/_components/EventBottom.module.scss
  src/app/event/_components/EventBottom.tsx
  src/app/event/_components/EventTab.module.scss
  src/app/event/_components/EventTab.tsx
  src/app/event/_components/EventTitle.module.scss
  src/app/event/_components/EventTitle.tsx
  src/app/event/_components/EventTop.module.scss
  src/app/event/_components/EventTop.tsx
  src/app/event/_components/Wheel.module.scss
  src/app/event/_components/Wheel.tsx
  src/app/event/_components/index.ts
  src/app/event/layout.tsx
  src/app/event/page.module.scss
  src/app/event/page.tsx
  src/app/my-info/(account)/coupons/_components/CouponList.tsx
  src/app/my-info/(account)/coupons/page.tsx
  src/app/shop/_components/Category/CategoryMenu.module.scss
  src/app/shop/_components/Category/CategoryMenu.tsx
  src/components/Buttons/HeartButton/HeartButton.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Pagination/Pagination.module.scss
  src/components/Products/ProductItem.tsx
  src/components/SignInModal/SignInModal.tsx
  src/constants/event.ts
  src/constants/route.ts
  src/hooks/useCreateCouponMutation.ts
  src/hooks/useKakaoShare.ts
  src/hooks/useMultipleIntersectionObservers.ts
  src/libs/wheelUtils.ts
  src/styles/globals/_fonts.scss
  src/styles/reset.css
  src/types/couponType.ts
Labels: 📖 Page, 📬 API, ✨ Component

#179 [Deploy] 새벽에 발생한 build 에러 해결 및 삭제 파일 복구
  package-lock.json
  src/app/my-info/(account)/coupons/page.tsx
Labels: 🌏 Deploy, 🐞 Fix

#180 [Fix] 대소문자 파일명 수정
  public/svgs/failIcon.svg
Labels: 🐞 Fix

#183 [Fix] 결제 Flow 디테일 수정 & 결제페이지 버그 수정
  deploy.sh
  package-lock.json
  package.json
  public/opengraph-image.png
  public/svgs/failIcon.svg
  src/api/orderAPI.ts
  src/api/shippingAPI.ts
  src/app/layout.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/Address/Address.module.scss
  src/app/my-info/(account)/addresses/_components/Addresses/Addresses.tsx
  src/app/my-info/(account)/addresses/_components/Addresses/AddressesEmptyCase/AddressesEmptyCase.module.scss
  src/app/my-info/(account)/addresses/_components/Addresses/AddressesEmptyCase/AddressesEmptyCase.tsx
  src/app/my-info/(account)/addresses/_components/AddressesHeader/AddressesHeader.module.scss
  src/app/payment/_components/CheckoutForm/CheckoutForm.module.scss
  src/app/payment/_components/CheckoutForm/CheckoutForm.tsx
  src/app/payment/_components/CheckoutForm/parts/CheckoutAddress.module.scss
  src/app/payment/_components/CheckoutForm/parts/CheckoutAddress.tsx
  src/app/payment/_components/CheckoutForm/parts/CheckoutAddressEmptyCase.module.scss
  src/app/payment/_components/CheckoutForm/parts/CheckoutAddressEmptyCase.tsx
  src/app/payment/_components/CheckoutForm/parts/CheckoutAddressModal.tsx
  src/app/payment/_components/CheckoutForm/parts/PaymentContainer.module.scss
  src/app/payment/_components/CheckoutForm/parts/PaymentContainer.tsx
  src/app/providers.tsx
  src/app/shop/_components/Category/CategoryMenu.module.scss
  src/app/shop/_components/Category/CategoryMenu.tsx
  src/components/AddAddressModal/AddAddressModal.module.scss
  src/components/AddAddressModal/AddAddressModal.tsx
  src/components/Header/HeaderParts/ShopButton.tsx
  src/styles/globals/_colors.scss
Labels: 🐞 Fix, 🎨 Style

#187 [Fix] 알림 페이지 이동 오류 수정
  src/components/Header/HeaderParts/NotificationCard.tsx
Labels: 🐞 Fix

#189 [Fix]interceptor Content-Type 적용 변경
  src/api/communityAPI.ts
  src/api/interceptor/interceptor.ts
  src/app/shop/[category]/[productId]/_components/Product/OptionWithButtons.tsx
Labels: 🐞 Fix

#185 [Feat] fix 버그 수정 및 이벤트 노출
  next.config.mjs
  public/fonts/Pretendard-Black.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-ExtraLight.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/Pretendard-Thin.woff2
  public/fonts/pretendard.ts
  public/images/banner2.png
  src/app/_components/Banner/Banner.tsx
  src/app/event/_components/AdvertisePanel.module.scss
  src/app/event/_components/AdvertisePanel.tsx
  src/app/event/_components/BenefitDelivery.module.scss
  src/app/event/_components/BenefitJoin.module.scss
  src/app/event/_components/BenefitJoin.tsx
  src/app/event/_components/BenefitRoulette.module.scss
  src/app/event/_components/BenefitRoulette.tsx
  src/app/event/_components/EventTop.module.scss
  src/app/event/_components/Roulette.module.scss
  src/app/event/_components/Roulette.tsx
  src/app/event/layout.tsx
  src/app/layout.tsx
  src/app/providers.module.scss
  src/app/providers.tsx
  src/components/Buttons/ScrollUpButton/ScrollUpButton.module.scss
  src/components/CountInput/CountInput.tsx
  src/constants/product.ts
  src/constants/route.ts
Labels: 🐞 Fix, 🎨 Style

#184 [Fix] 버그 수정 (민정)
  src/api/authAPI.ts
  src/api/communityAPI.ts
  src/api/likesAPI.ts
  src/app/(auth)/sign-up/_component/SignupForm.module.scss
  src/app/(auth)/sign-up/_component/SignupForm.tsx
  src/app/(auth)/sign-up/_component/TermsAgreement.module.scss
  src/app/(auth)/sign-up/_component/TermsAgreement.tsx
  src/app/community/_components/Comment.tsx
  src/app/community/_components/UserProfileCard.module.scss
  src/app/community/_components/UserProfileCard.tsx
  src/app/community/_components/WritePostButton.tsx
  src/app/my-info/(account)/coupons/_components/CouponEmptyCase.module.scss
  src/app/my-info/(account)/coupons/_components/CouponEmptyCase.tsx
  src/app/my-info/(account)/coupons/page.tsx
  src/components/Buttons/HeartButton/HeartButton.tsx
  src/components/ImageZoom/ImageZoom.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/components/SignInModal/SignInModal.tsx
  src/components/SignInModal/SigninModal.module.scss
  src/components/TextField/TextField.tsx
  src/components/WriteEditModal/WriteEditModal.module.scss
  src/components/WriteEditModal/WriteEditModal.tsx
  src/constants/route.ts
  src/styles/globals/_fonts.scss
  src/types/communityType.ts
  src/types/likeType.ts
Labels: 🐞 Fix

#192 [Fix] my info 페이지 토큰 변조 대비
  src/api/interceptor/interceptor.ts
  src/app/my-info/(account)/coupons/page.tsx
  src/app/my-info/(account)/my-posts/_components/MyPostCardList.tsx
  src/app/my-info/(account)/my-posts/page.tsx
  src/app/my-info/(account)/wishlist/_components/WishList.tsx
  src/app/my-info/layout.tsx
  src/components/Skeleton/Skeleton.tsx
  src/constants/initialParams.ts
Labels: 🐞 Fix, 📬 API
